spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:testdb/testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  messages:
    basename: messages
logging:
    file: logs/myapp.log
    level:
        org.springframework.web: DEBUG
